# Generated by Django 2.2.3 on 2019-07-16 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('imagen', models.TextField()),
                ('fabricante', models.TextField()),
                ('descripcion', models.TextField()),
                ('precio', models.FloatField()),
                ('porc_descuento', models.FloatField()),
                ('iva', models.FloatField()),
                ('unidades', models.IntegerField()),
                ('detalles', models.TextField()),
            ],
        ),
    ]
