# Generated by Django 2.2.3 on 2019-07-15 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Producto',
        ),
    ]
