# Generated by Django 2.2.3 on 2019-07-16 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proovedor',
            fields=[
                ('nit', models.IntegerField(primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=20)),
                ('telefono', models.CharField(max_length=10)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
