# Generated by Django 2.2.3 on 2019-07-16 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('nombre', models.TextField()),
                ('tipo_documento', models.TextField()),
                ('num_documento', models.IntegerField(primary_key=True, serialize=False)),
                ('telefono', models.IntegerField()),
                ('direccion', models.TextField()),
                ('fecha_nacimiento', models.DateField()),
            ],
        ),
    ]
