# Generated by Django 2.2.3 on 2019-07-16 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('codigo_factura', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('subtotal', models.FloatField()),
                ('total', models.FloatField()),
            ],
        ),
    ]
